server:
  port: 9001
spring:
  application:
    name: tensquare-base #指定应用名称 后边使用SpringCloud管理微服务会用到

#数据库相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.237.204:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
#jpa相关配置
  jpa:
    generate-ddl: false #自动建表
    show-sql: true
    database: mysql
    #database-platform: #

# 注册中心
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka

jwt:
  config:
    key: itcast
