server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.237.204:3306/tensquare_gathering?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 47.93.237.204
    port: 36379
    password: 123456
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka