server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.237.204:3306/tensquare_qa?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true

feign:
  hystrix:
    enabled: true

jwt:
  config:
    key: itcast
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka

