server:
  port: 9007
spring:
  application:
    name: tensquare-search #指定应用名称 后边使用SpringCloud管理微服务会用到
  data:
    elasticsearch:
      repositories:
        enabled: true #开启 Elasticsearch 仓库(默认值:true)
      cluster-nodes: 47.93.237.204:9300 #默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口
      client:
        reactive:
          connection-timeout: 120s #连接超时的时间
      cluster-name: elasticsearch

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka





